api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    
]

home/__pycache__/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.Index.as_view(), name="Index")
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from core.models import Area
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=128, default="I Love Plesem System")
    avatar = models.ImageField(blank=True, null=True)
    timestamp = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8, unique=True) 

    def __srt__(self):
        return self.user.first_name
    
@receiver(post_save, sender=User)
def auto_profile(sender, instance, **kwargs):
    if kwargs.get('created', False):
        Profile.objects.get_or_create(user=instance)

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control"}))
    password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control"}))



class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Username"})) 
    password1 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escribe tu Password"}))
    password2 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Confirma tu Password"}))  
    first_name = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu First Name"})) 
    last_name = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Last Name"})) 
    email = forms.EmailField(max_length=32, widget=forms.EmailInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Email"})) 

home/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy

from .forms import LoginForm, SignUpForm

# Create your views here.

class Index(generic.View):
    template_name = "home/index.html"
    context = {}
    form_class = LoginForm

    def get(self, request):
        self.context = {
            "users": User.objects.all(),
            "form": self.form_class
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            redirect("home:index")
        return redirect("home:index")




class Logout(generic.View):
    def get(self, request):
        logout(request)
        return redirect("home:index")
    


class SignUp(generic.CreateView):
    template_name = "home/signup.html"
    model = User
    form_class = SignUpForm
    success_url = reverse_lazy("home:index")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password1 = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password1)
        if user is not None:
            login(self.request, user)
        return redirect("home:index")

        
    

templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}INDEX VIEW {% endblock title %}

   <h1>Hola Mundo Django XD ...</h1>

   {% block content %}
      {% if request.user.is_authenticated %}  
      <h3>Welcome User: "{{ request.user.username }}" to Plesem System!!</h3>
        <table class="table table-striped">
            <thead>
                <th>ID</th>
                <th>Name</th>
                <th>EMAIL</th>
                <th></th>
                <th>ACTIONS</th>
                <th></th>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email}}</td>
                        <td><a href="" class="btn btn-outline-info">detail</a></td>
                        <td><a href="" class="btn btn-outline-warning">update</a></td>
                        <td><a href="" class="btn btn-outline-danger">delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <form action="" method="post">
                {% csrf_token %}
                    {{ form }}
                <button type="submit" class="btn btn-primary form-control">LogIn</button>
                <a href="{% url 'home:index' %}" class="btn btn-warning form-control">Cancel</a>
            </form>
            <h4>Si no tienes una cuenta, Registrate <a href="{% url 'home:signup' %}">Aqui</a></h4>
        {% endif %}
        
{% endblock content %}

templates/home/signup.html
{% extends "base/base.html" %}

{% block title %}SIGNUP VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-success form-control">SignUp</button>
            <a href="{% url 'home:index' %}" class="btn btn-warning">Cancel</a>
    </form>
{% endblock content %}